//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties {


	/// <summary>
	///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
	/// </summary>
	// このクラスは StronglyTypedResourceBuilder クラスが ResGen
	// または Visual Studio のようなツールを使用して自動生成されました。
	// メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
	// ResGen を実行し直すか、または VS プロジェクトをリビルドします。
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0" )]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
		internal Resources() {
		}

		/// <summary>
		///   このクラスに使用される、キャッシュされた ResourceManager のインスタンスを返します。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if ( ( resourceMan == null ) ) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "ElectronicObserver.Properties.Resources", typeof( Resources ).Assembly );
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
		///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
        
        /// <summary>
        ///   陸上基地 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Constant_LandBase {
            get {
                return ResourceManager.GetString("Constant_LandBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Constant_Null {
            get {
                return ResourceManager.GetString("Constant_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   演習 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Constant_Practice {
            get {
                return ResourceManager.GetString("Constant_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Constant_Unknown {
            get {
                return ResourceManager.GetString("Constant_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備ID,図鑑番号,装備名,装備種1,装備種2,装備種3,装備種4,火力,雷装,対空,装甲,対潜,回避,索敵,運,命中,爆装,射程,レア,廃棄燃料,廃棄弾薬,廃棄鋼材,廃棄ボーキ,図鑑文章,バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_DataCSVHeader {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_DataCSVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備図鑑 -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_EquipmentAlbum {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_EquipmentAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備図鑑 CSVの出力に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_ExportCSVError {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_ExportCSVError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備可能艦種: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_ShipEquiped {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_ShipEquiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備ID,図鑑番号,装備種,装備名,装備種1,装備種2,装備種3,装備種4,火力,雷装,対空,装甲,対潜,回避,索敵,運,命中,爆装,射程,レア,廃棄燃料,廃棄弾薬,廃棄鋼材,廃棄ボーキ,図鑑文章,バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_UserCSVHeader {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_UserCSVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_AAInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_AAInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   命中 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_AccuracyInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_AccuracyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装甲 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_ArmorInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_ArmorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対潜 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_ASWInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_ASWInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_BasicValue {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_BasicValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   爆装 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_BomberInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_BomberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (右クリックで図鑑) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_ClickToOpenAlbum {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_ClickToOpenAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船ID,図鑑番号,艦名,読み,艦種,改装前,改装後,改装Lv,改装弾薬,改装鋼材,改装設計図,耐久初期,耐久最大,耐久結婚,火力初期,火力最大,雷装初期,雷装最大,対空初期,対空最大,装甲初期,装甲最大,対潜初期最小,対潜初期最大,対潜最大,対潜150最小,対潜150最大,回避初期最小,回避初期最大,回避最大,回避150最小,回避150最大,索敵初期最小,索敵初期最大,索敵最大,索敵150最小,索敵150最大,運初期,運最大,速力,射程,レア,スロット数,搭載機数1,搭載機数2,搭載機数3,搭載機数4,搭載機数5,初期装備1,初期装備2,初期装備3,初期装備4,初期装備5,建造時間,解体燃料,解体弾薬,解体鋼材,解体ボーキ,改修火力,改修雷装,改修対空,改修装甲,ドロップ文章,図鑑文章,搭載燃料,搭載弾薬,ボイス,リソース名,バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_DataCSVHeader {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_DataCSVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_EquippedValue {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_EquippedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回避 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_EvasionInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_EvasionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船図鑑 CSVの出力に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_ExportCSVError {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_ExportCSVError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火力 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_FirepowerInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_FirepowerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_InitValue {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_InitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_LOSInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_LOSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_MaxValue {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (なし) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_Null {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   枚 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_Paper {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠時の消費:
        ///HP1あたり: 鋼 {0:F2} / 燃 {1:F2}
        ///最大: 鋼 {2} / 燃 {3}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_RepairConsumeInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_RepairConsumeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船図鑑 -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_ShipAlbum {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_ShipAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   雷装 {0}{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_TorpedoInfo {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_TorpedoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船ID,図鑑番号,艦種,艦名,読み,改装前,改装後,改装Lv,改装弾薬,改装鋼材,改装設計図,耐久初期,耐久結婚,火力初期,火力最大,雷装初期,雷装最大,対空初期,対空最大,装甲初期,装甲最大,対潜初期,対潜最大,回避初期,回避最大,索敵初期,索敵最大,運初期,運最大,速力,射程,レア,スロット数,搭載機数1,搭載機数2,搭載機数3,搭載機数4,搭載機数5,初期装備1,初期装備2,初期装備3,初期装備4,初期装備5,建造時間,解体燃料,解体弾薬,解体鋼材,解体ボーキ,改修火力,改修雷装,改修対空,改修装甲,ドロップ文章,図鑑文章,搭載燃料,搭載弾薬,ボイス,リソース名,バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogAlbumMasterShip_UserCSVHeader {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_UserCSVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたフォルダは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogConfiguration_FolderNotFound {
            get {
                return ResourceManager.GetString("DialogConfiguration_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦これに接続してから操作してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogConfiguration_KanColleNotLoaded {
            get {
                return ResourceManager.GetString("DialogConfiguration_KanColleNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動プロキシ設定スクリプトを保存し、設定用URLをクリップボードにコピーしました。
        ///所定の位置に貼り付けてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogConfiguration_PACSaved {
            get {
                return ResourceManager.GetString("DialogConfiguration_PACSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動プロキシ設定スクリプトを保存する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogConfiguration_PACSaveDialogTitle {
            get {
                return ResourceManager.GetString("DialogConfiguration_PACSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動プロキシ設定スクリプトの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogConfiguration_PACSaveError {
            get {
                return ResourceManager.GetString("DialogConfiguration_PACSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogConfigurationNotifier_ImageLoadError {
            get {
                return ResourceManager.GetString("DialogConfigurationNotifier_ImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogConfigurationNotifier_SoundLoadError {
            get {
                return ResourceManager.GetString("DialogConfigurationNotifier_SoundLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト 通知です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogConfigurationNotifier_TestMessage {
            get {
                return ResourceManager.GetString("DialogConfigurationNotifier_TestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormArsenal_Complete {
            get {
                return ResourceManager.GetString("FormArsenal_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了日時 :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormArsenal_CompleteTime {
            get {
                return ResourceManager.GetString("FormArsenal_CompleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空砲火 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AAAttack {
            get {
                return ResourceManager.GetString("FormBattle_AAAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空カットイン: {0}
        ///カットイン種別: {1} ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AAAttackInfo {
            get {
                return ResourceManager.GetString("FormBattle_AAAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空カットイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AACutIn {
            get {
                return ResourceManager.GetString("FormBattle_AACutIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第{0}次: {1}
        ///カットイン種別: {2} ({3})
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AACutInAttackInfo {
            get {
                return ResourceManager.GetString("FormBattle_AACutInAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第{0}次: (発動せず)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AACutInNoneInfo {
            get {
                return ResourceManager.GetString("FormBattle_AACutInNoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第1次: -{0}/{1}
        ///第2次: -{2}/{3}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AirStageAttackInfo {
            get {
                return ResourceManager.GetString("FormBattle_AirStageAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}触接中
        ///第1次: {1}
        ///第2次: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AirStageTouchInfo {
            get {
                return ResourceManager.GetString("FormBattle_AirStageTouchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   照明弾投射:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_Flare {
            get {
                return ResourceManager.GetString("FormBattle_Flare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夜間触接 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_MidnightTouch {
            get {
                return ResourceManager.GetString("FormBattle_MidnightTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夜間触接中:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_MidnightTouching {
            get {
                return ResourceManager.GetString("FormBattle_MidnightTouching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (なし) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_Null {
            get {
                return ResourceManager.GetString("FormBattle_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   探照灯照射:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_SearchLight {
            get {
                return ResourceManager.GetString("FormBattle_SearchLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   触接中:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_Touching {
            get {
                return ResourceManager.GetString("FormBattle_Touching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第2次:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_Twice {
            get {
                return ResourceManager.GetString("FormBattle_Twice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザの終了中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_BrowserCloseError {
            get {
                return ResourceManager.GetString("FormBrowserHost_BrowserCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザプロセスが予期せず終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_BrowserNotFound {
            get {
                return ResourceManager.GetString("FormBrowserHost_BrowserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザプロセス間で通信エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_CommunicateError {
            get {
                return ResourceManager.GetString("FormBrowserHost_CommunicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先の URL を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_NavigateMessage {
            get {
                return ResourceManager.GetString("FormBrowserHost_NavigateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先の入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_NavigateTitle {
            get {
                return ResourceManager.GetString("FormBrowserHost_NavigateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザプロセスの起動に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_StartUpFail {
            get {
                return ResourceManager.GetString("FormBrowserHost_StartUpFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_AAInfo {
            get {
                return ResourceManager.GetString("FormCompass_AAInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///昼戦: {0}
        ///夜戦: {1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_AttackInfo {
            get {
                return ResourceManager.GetString("FormCompass_AttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    (終点) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_EndPoint {
            get {
                return ResourceManager.GetString("FormCompass_EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   敵艦隊ID : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_EnemyIDInfo {
            get {
                return ResourceManager.GetString("FormCompass_EnemyIDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃海域 : {0}-{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_MapAreaInfo {
            get {
                return ResourceManager.GetString("FormCompass_MapAreaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のセル : {0}{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_NextPointInfo {
            get {
                return ResourceManager.GetString("FormCompass_NextPointInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵機発艦！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_Seaplane {
            get {
                return ResourceManager.GetString("FormCompass_Seaplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1}{2}
        ///耐久: {3}
        ///火力: {4}/{5}
        ///雷装: {6}/{7}
        ///対空: {8}/{9}
        ///装甲: {10}/{11}
        ///対潜: {12}/{13}
        ///回避: {14}/{15}
        ///索敵: {16}/{17}
        ///運: {18}/{19}
        ///(右クリックで図鑑)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_ShipInfo {
            get {
                return ResourceManager.GetString("FormCompass_ShipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (敵艦隊情報不明) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_UnknownEnemy {
            get {
                return ResourceManager.GetString("FormCompass_UnknownEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   どうしてこうなった に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_UnknownEventID {
            get {
                return ResourceManager.GetString("FormCompass_UnknownEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   謎のアイテム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_UnknownItem {
            get {
                return ResourceManager.GetString("FormCompass_UnknownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了日時 :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormDock_CompleteTime {
            get {
                return ResourceManager.GetString("FormDock_CompleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}\t制空戦力{1}/索敵能力{2}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_AA_LOSInfo {
            get {
                return ResourceManager.GetString("FormFleet_AA_LOSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確保: {0}
        ///優勢: {1}
        ///均衡: {2}
        ///劣勢: {3}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_AAInfo {
            get {
                return ResourceManager.GetString("FormFleet_AAInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計レベル：{0}
        ///平均レベル：{1:0.00}
        ///ドラム缶搭載: {2}個 ({3}艦)
        ///大発動艇搭載: {4}個
        ///総積載: 燃 {5} / 弾 {6}
        ///(1戦当たり 燃 {7} / 弾 {8}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_FleetInfo {
            get {
                return ResourceManager.GetString("FormFleet_FleetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *nothing* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_FleetNameNull {
            get {
                return ResourceManager.GetString("FormFleet_FleetNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (旧)2-5式: {0}
        ///2-5式(秋): {1}
        ///2-5新秋簡易式: {2}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_LOSInfo {
            get {
                return ResourceManager.GetString("FormFleet_LOSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipAAInfo {
            get {
                return ResourceManager.GetString("FormFleet_ShipAAInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///昼戦: {0}
        ///夜戦: {1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipAttackInfo {
            get {
                return ResourceManager.GetString("FormFleet_ShipAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠時間: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipDockTime {
            get {
                return ResourceManager.GetString("FormFleet_ShipDockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   退避中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipEscaped {
            get {
                return ResourceManager.GetString("FormFleet_ShipEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1}
        ///火力: {2}/{3}
        ///雷装: {4}/{5}
        ///対空: {6}/{7}
        ///装甲: {8}/{9}
        ///対潜: {10}/{11}
        ///回避: {12}/{13}
        ///索敵: {14}/{15}
        ///運: {16}
        ///(右クリックで図鑑)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipInfo {
            get {
                return ResourceManager.GetString("FormFleet_ShipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv150まで: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipLevel150Exp {
            get {
                return ResourceManager.GetString("FormFleet_ShipLevel150Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv99まで: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipLevel99Exp {
            get {
                return ResourceManager.GetString("FormFleet_ShipLevel99Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大破しています！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipLowHP {
            get {
                return ResourceManager.GetString("FormFleet_ShipLowHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のレベルまで: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipNextLevelExp {
            get {
                return ResourceManager.GetString("FormFleet_ShipNextLevelExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改装まで: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipRemodelExp {
            get {
                return ResourceManager.GetString("FormFleet_ShipRemodelExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あと {0} 回遠征可能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipSparkleExpeditionTime {
            get {
                return ResourceManager.GetString("FormFleet_ShipSparkleExpeditionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大破まで: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipToLowHP {
            get {
                return ResourceManager.GetString("FormFleet_ShipToLowHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中破まで: {0} / 大破まで: {1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipToMidHP {
            get {
                return ResourceManager.GetString("FormFleet_ShipToMidHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完全回復まで 約 {0:D2}:{1:D2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormFleet_ShipToNormalCond {
            get {
                return ResourceManager.GetString("FormFleet_ShipToNormalCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [未保有装備] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Album_EquipmentNotCollected {
            get {
                return ResourceManager.GetString("FormInformation_Album_EquipmentNotCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [中破絵未回収] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Album_MidHPNotCollected {
            get {
                return ResourceManager.GetString("FormInformation_Album_MidHPNotCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [未保有艦] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Album_ShipNotCollected {
            get {
                return ResourceManager.GetString("FormInformation_Album_ShipNotCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [開発失敗] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_CreateItem_Failed {
            get {
                return ResourceManager.GetString("FormInformation_CreateItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提督経験値: +{0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Expedition_AdmiralExpInfo {
            get {
                return ResourceManager.GetString("FormInformation_Expedition_AdmiralExpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Expedition_ResultInfo {
            get {
                return ResourceManager.GetString("FormInformation_Expedition_ResultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦娘経験値: +{0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Expedition_ShipExpInfo {
            get {
                return ResourceManager.GetString("FormInformation_Expedition_ShipExpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [遠征帰投] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Expedition_Title {
            get {
                return ResourceManager.GetString("FormInformation_Expedition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}-{1} : 撃破 {2}/{3} 回
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Map_BossDefeatInfo {
            get {
                return ResourceManager.GetString("FormInformation_Map_BossDefeatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [海域ゲージ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Map_BossHP {
            get {
                return ResourceManager.GetString("FormInformation_Map_BossHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   敵艦隊名 :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Practice_EnemyFleetName {
            get {
                return ResourceManager.GetString("FormInformation_Practice_EnemyFleetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   獲得経験値 :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Practice_GainExp {
            get {
                return ResourceManager.GetString("FormInformation_Practice_GainExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S勝利 :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Practice_GainSExp {
            get {
                return ResourceManager.GetString("FormInformation_Practice_GainSExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [演習情報] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormInformation_Practice_Title {
            get {
                return ResourceManager.GetString("FormInformation_Practice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIリストをロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_APIListOpenDialogTitle {
            get {
                return ResourceManager.GetString("FormMain_APIListOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_APIReadError {
            get {
                return ResourceManager.GetString("FormMain_APIReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在: {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_BrowserZoomText {
            get {
                return ResourceManager.GetString("FormMain_BrowserZoomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了処理が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_CloseComplete {
            get {
                return ResourceManager.GetString("FormMain_CloseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブしていないレコードが失われる可能性があります。
        ///ロードしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_DataNotSavedMessage {
            get {
                return ResourceManager.GetString("FormMain_DataNotSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備データが読み込まれていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_EquipmentDataNotLoaded {
            get {
                return ResourceManager.GetString("FormMain_EquipmentDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部ブラウザでオンラインヘルプを開きます。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_HelpMessage {
            get {
                return ResourceManager.GetString("FormMain_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウト ファイルは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutFileNotFound {
            get {
                return ResourceManager.GetString("FormMain_LayoutFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトが初期化されました。
        ///「表示」メニューからお好みのウィンドウを追加してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutInitializeMessage {
            get {
                return ResourceManager.GetString("FormMain_LayoutInitializeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウトを復元しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutLoadComplete {
            get {
                return ResourceManager.GetString("FormMain_LayoutLoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウトの復元に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutLoadError {
            get {
                return ResourceManager.GetString("FormMain_LayoutLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト ファイルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutOpenDialogTitle {
            get {
                return ResourceManager.GetString("FormMain_LayoutOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウトを保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutSaveComplete {
            get {
                return ResourceManager.GetString("FormMain_LayoutSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウトの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutSaveError {
            get {
                return ResourceManager.GetString("FormMain_LayoutSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動処理が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LoadComplete {
            get {
                return ResourceManager.GetString("FormMain_LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先に通常の api_start2 を読み込んでください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LoadOldAPINeedDataMessage {
            get {
                return ResourceManager.GetString("FormMain_LoadOldAPINeedDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先の URL を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_NavigateMessage {
            get {
                return ResourceManager.GetString("FormMain_NavigateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先の入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_NavigateTitle {
            get {
                return ResourceManager.GetString("FormMain_NavigateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインページへ移動します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_NavigateToLoginMessage {
            get {
                return ResourceManager.GetString("FormMain_NavigateToLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除が完了しました。
        ///{0} 個のファイルを削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_OldAPIDeleteComplete {
            get {
                return ResourceManager.GetString("FormMain_OldAPIDeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_OldAPIDeleteError {
            get {
                return ResourceManager.GetString("FormMain_OldAPIDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   古いAPIデータを削除します。
        ///本当によろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_OldAPIDeleteMessage {
            get {
                return ResourceManager.GetString("FormMain_OldAPIDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旧 api_start2 からレコードを構築 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_OldAPIOpenDialogTitle {
            get {
                return ResourceManager.GetString("FormMain_OldAPIOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を終了しています… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_Quit {
            get {
                return ResourceManager.GetString("FormMain_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を終了しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_QuitMessage {
            get {
                return ResourceManager.GetString("FormMain_QuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リネーム処理が完了しました。
        ///{0} 個のアイテムをリネームしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_RenameShipResourceComplete {
            get {
                return ResourceManager.GetString("FormMain_RenameShipResourceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船リソースのリネームに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_RenameShipResourceError {
            get {
                return ResourceManager.GetString("FormMain_RenameShipResourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信から保存した艦船リソース名を持つファイル及びフォルダを、艦船名に置換します。
        ///対象は指定されたフォルダ以下のすべてのファイル及びフォルダです。
        ///続行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_RenameShipResourceMessage {
            get {
                return ResourceManager.GetString("FormMain_RenameShipResourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船リソースをリネーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_RenameShipResourceTitle {
            get {
                return ResourceManager.GetString("FormMain_RenameShipResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船データが読み込まれていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_ShipDataNotLoaded {
            get {
                return ResourceManager.GetString("FormMain_ShipDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を起動しています… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_StartUp {
            get {
                return ResourceManager.GetString("FormMain_StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブウィンドウ レイアウトの復元に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_SubLayoutLoadError {
            get {
                return ResourceManager.GetString("FormMain_SubLayoutLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブウィンドウ レイアウトの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_SubLayoutSaveError {
            get {
                return ResourceManager.GetString("FormMain_SubLayoutSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   達成！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormQuest_Complete {
            get {
                return ResourceManager.GetString("FormQuest_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任務データを初期化します。
        ///データに齟齬が生じている場合以外での使用は推奨しません。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormQuest_InitializeMessage {
            get {
                return ResourceManager.GetString("FormQuest_InitializeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任務初期化の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormQuest_InitializeTitle {
            get {
                return ResourceManager.GetString("FormQuest_InitializeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50%以上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormQuest_Progress50 {
            get {
                return ResourceManager.GetString("FormQuest_Progress50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   80%以上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormQuest_Progress80 {
            get {
                return ResourceManager.GetString("FormQuest_Progress80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (任務完遂！) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormQuest_QuestComplete {
            get {
                return ResourceManager.GetString("FormQuest_QuestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (未取得) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormQuest_UnknownQuest {
            get {
                return ResourceManager.GetString("FormQuest_UnknownQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (未取得の任務 x {0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormQuest_UnknownQuestInfo {
            get {
                return ResourceManager.GetString("FormQuest_UnknownQuestInfo", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   対空 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_AA {
            get {
                return ResourceManager.GetString("FormShipGroup_AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空改修 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_AARemain {
            get {
                return ResourceManager.GetString("FormShipGroup_AARemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加するグループを選択してください： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_AddToGroupMessage {
            get {
                return ResourceManager.GetString("FormShipGroup_AddToGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_AddToGroupTitle {
            get {
                return ResourceManager.GetString("FormShipGroup_AddToGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   弾薬 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Ammo {
            get {
                return ResourceManager.GetString("FormShipGroup_Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   固有ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_APIID {
            get {
                return ResourceManager.GetString("FormShipGroup_APIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装甲 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Armor {
            get {
                return ResourceManager.GetString("FormShipGroup_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装甲改修 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ArmorRemain {
            get {
                return ResourceManager.GetString("FormShipGroup_ArmorRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対潜 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ASW {
            get {
                return ResourceManager.GetString("FormShipGroup_ASW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cond に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Condition {
            get {
                return ResourceManager.GetString("FormShipGroup_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加するグループの名前を入力してください： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_CreateGroupMessage {
            get {
                return ResourceManager.GetString("FormShipGroup_CreateGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループの追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_CreateGroupTitle {
            get {
                return ResourceManager.GetString("FormShipGroup_CreateGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Equipment1 {
            get {
                return ResourceManager.GetString("FormShipGroup_Equipment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Equipment2 {
            get {
                return ResourceManager.GetString("FormShipGroup_Equipment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Equipment3 {
            get {
                return ResourceManager.GetString("FormShipGroup_Equipment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Equipment4 {
            get {
                return ResourceManager.GetString("FormShipGroup_Equipment4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Equipment5 {
            get {
                return ResourceManager.GetString("FormShipGroup_Equipment5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回避 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Evasion {
            get {
                return ResourceManager.GetString("FormShipGroup_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Exp {
            get {
                return ResourceManager.GetString("FormShipGroup_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船グループ CSVの出力に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ExportCSVError {
            get {
                return ResourceManager.GetString("FormShipGroup_ExportCSVError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Firepower {
            get {
                return ResourceManager.GetString("FormShipGroup_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火力改修 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_FirepowerRemain {
            get {
                return ResourceManager.GetString("FormShipGroup_FirepowerRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   燃料 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Fuel {
            get {
                return ResourceManager.GetString("FormShipGroup_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ名を入力してください： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_GroupAddMessage {
            get {
                return ResourceManager.GetString("FormShipGroup_GroupAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループを追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_GroupAddTitle {
            get {
                return ResourceManager.GetString("FormShipGroup_GroupAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このグループは削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_GroupDeleteError {
            get {
                return ResourceManager.GetString("FormShipGroup_GroupDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ [{0}] を削除しますか？
        ///この操作は元に戻せません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_GroupDeleteMessage {
            get {
                return ResourceManager.GetString("FormShipGroup_GroupDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー：存在しないグループを参照しようとしました。開発者に連絡してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_GroupNull {
            get {
                return ResourceManager.GetString("FormShipGroup_GroupNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   耐久最大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_HPMax {
            get {
                return ResourceManager.GetString("FormShipGroup_HPMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   耐久現在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_HPNow {
            get {
                return ResourceManager.GetString("FormShipGroup_HPNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Level {
            get {
                return ResourceManager.GetString("FormShipGroup_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平均Lv: {0:F2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_LevelAverageInfo {
            get {
                return ResourceManager.GetString("FormShipGroup_LevelAverageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計Lv: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_LevelTotalInfo {
            get {
                return ResourceManager.GetString("FormShipGroup_LevelTotalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Locked {
            get {
                return ResourceManager.GetString("FormShipGroup_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_LOS {
            get {
                return ResourceManager.GetString("FormShipGroup_LOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Luck {
            get {
                return ResourceManager.GetString("FormShipGroup_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運改修 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_LuckRemain {
            get {
                return ResourceManager.GetString("FormShipGroup_LuckRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このグループは変更できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ModifyGroupError {
            get {
                return ResourceManager.GetString("FormShipGroup_ModifyGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_NextLevelExp {
            get {
                return ResourceManager.GetString("FormShipGroup_NextLevelExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦載機1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Plane1 {
            get {
                return ResourceManager.GetString("FormShipGroup_Plane1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦載機2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Plane2 {
            get {
                return ResourceManager.GetString("FormShipGroup_Plane2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦載機3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Plane3 {
            get {
                return ResourceManager.GetString("FormShipGroup_Plane3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦載機4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Plane4 {
            get {
                return ResourceManager.GetString("FormShipGroup_Plane4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦載機5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Plane5 {
            get {
                return ResourceManager.GetString("FormShipGroup_Plane5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改装まで に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_RemodelExp {
            get {
                return ResourceManager.GetString("FormShipGroup_RemodelExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Repair {
            get {
                return ResourceManager.GetString("FormShipGroup_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠 # に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_RepairInfo {
            get {
                return ResourceManager.GetString("FormShipGroup_RepairInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_SallyArea {
            get {
                return ResourceManager.GetString("FormShipGroup_SallyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所属: {0}隻 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ShipCountInfo {
            get {
                return ResourceManager.GetString("FormShipGroup_ShipCountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ShipID {
            get {
                return ResourceManager.GetString("FormShipGroup_ShipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ShipKind {
            get {
                return ResourceManager.GetString("FormShipGroup_ShipKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全所属艦 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ShipKindDefault {
            get {
                return ResourceManager.GetString("FormShipGroup_ShipKindDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ShipName {
            get {
                return ResourceManager.GetString("FormShipGroup_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   射程 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_ShootRange {
            get {
                return ResourceManager.GetString("FormShipGroup_ShootRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   雷装 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_Torpedo {
            get {
                return ResourceManager.GetString("FormShipGroup_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   雷装改修 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGroup_TorpedoRemain {
            get {
                return ResourceManager.GetString("FormShipGroup_TorpedoRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このグループの名前を変更することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGruop_GroupRenameError {
            get {
                return ResourceManager.GetString("FormShipGruop_GroupRenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ名を入力してください： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGruop_GroupRenameMessage {
            get {
                return ResourceManager.GetString("FormShipGruop_GroupRenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ名の変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormShipGruop_GroupRenameTitle {
            get {
                return ResourceManager.GetString("FormShipGruop_GroupRenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Complete {
            get {
                return ResourceManager.GetString("MessageBox_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Confirm {
            get {
                return ResourceManager.GetString("MessageBox_Confirm", resourceCulture);
            }
        }

        
        /// <summary>
        ///   作成完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_CreateComplete {
            get {
                return ResourceManager.GetString("MessageBox_CreateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_DeleteComplete {
            get {
                return ResourceManager.GetString("MessageBox_DeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Error {
            get {
                return ResourceManager.GetString("Messagebox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Help {
            get {
                return ResourceManager.GetString("MessageBox_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大変ご迷惑をおかけしております に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_MeetError {
            get {
                return ResourceManager.GetString("Messagebox_MeetError", resourceCulture);
            }
        }
    }
}
