//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties {


	/// <summary>
	///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
	/// </summary>
	// このクラスは StronglyTypedResourceBuilder クラスが ResGen
	// または Visual Studio のようなツールを使用して自動生成されました。
	// メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
	// ResGen を実行し直すか、または VS プロジェクトをリビルドします。
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0" )]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
		internal Resources() {
		}

		/// <summary>
		///   このクラスに使用される、キャッシュされた ResourceManager のインスタンスを返します。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if ( ( resourceMan == null ) ) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "ElectronicObserver.Properties.Resources", typeof( Resources ).Assembly );
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
		///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Constant_Null {
            get {
                return ResourceManager.GetString("Constant_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   演習 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Constant_Practice {
            get {
                return ResourceManager.GetString("Constant_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Constant_Unknown {
            get {
                return ResourceManager.GetString("Constant_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormArsenal_Complete {
            get {
                return ResourceManager.GetString("FormArsenal_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了日時 :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormArsenal_CompleteTime {
            get {
                return ResourceManager.GetString("FormArsenal_CompleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空砲火 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AAAttack {
            get {
                return ResourceManager.GetString("FormBattle_AAAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空カットイン: {0}
        ///カットイン種別: {1} ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AAAttackInfo {
            get {
                return ResourceManager.GetString("FormBattle_AAAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空カットイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AACutIn {
            get {
                return ResourceManager.GetString("FormBattle_AACutIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第{0}次: {1}
        ///カットイン種別: {2} ({3})
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AACutInAttackInfo {
            get {
                return ResourceManager.GetString("FormBattle_AACutInAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第{0}次: (発動せず)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AACutInNoneInfo {
            get {
                return ResourceManager.GetString("FormBattle_AACutInNoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第1次: -{0}/{1}
        ///第2次: -{2}/{3}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AirStageAttackInfo {
            get {
                return ResourceManager.GetString("FormBattle_AirStageAttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}触接中
        ///第1次: {1}
        ///第2次: {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_AirStageTouchInfo {
            get {
                return ResourceManager.GetString("FormBattle_AirStageTouchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   照明弾投射:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_Flare {
            get {
                return ResourceManager.GetString("FormBattle_Flare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夜間触接 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_MidnightTouch {
            get {
                return ResourceManager.GetString("FormBattle_MidnightTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夜間触接中:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_MidnightTouching {
            get {
                return ResourceManager.GetString("FormBattle_MidnightTouching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (なし) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_Null {
            get {
                return ResourceManager.GetString("FormBattle_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   探照灯照射:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_SearchLight {
            get {
                return ResourceManager.GetString("FormBattle_SearchLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   触接中:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_Touching {
            get {
                return ResourceManager.GetString("FormBattle_Touching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   第2次:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBattle_Twice {
            get {
                return ResourceManager.GetString("FormBattle_Twice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザの終了中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_BrowserCloseError {
            get {
                return ResourceManager.GetString("FormBrowserHost_BrowserCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザプロセスが予期せず終了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_BrowserNotFound {
            get {
                return ResourceManager.GetString("FormBrowserHost_BrowserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザプロセス間で通信エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_CommunicateError {
            get {
                return ResourceManager.GetString("FormBrowserHost_CommunicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先の URL を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_NavigateMessage {
            get {
                return ResourceManager.GetString("FormBrowserHost_NavigateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先の入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_NavigateTitle {
            get {
                return ResourceManager.GetString("FormBrowserHost_NavigateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザプロセスの起動に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormBrowserHost_StartUpFail {
            get {
                return ResourceManager.GetString("FormBrowserHost_StartUpFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_AAInfo {
            get {
                return ResourceManager.GetString("FormCompass_AAInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///昼戦: {0}
        ///夜戦: {1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_AttackInfo {
            get {
                return ResourceManager.GetString("FormCompass_AttackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    (終点) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_EndPoint {
            get {
                return ResourceManager.GetString("FormCompass_EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   敵艦隊ID : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_EnemyIDInfo {
            get {
                return ResourceManager.GetString("FormCompass_EnemyIDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃海域 : {0}-{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_MapAreaInfo {
            get {
                return ResourceManager.GetString("FormCompass_MapAreaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のセル : {0}{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_NextPointInfo {
            get {
                return ResourceManager.GetString("FormCompass_NextPointInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵機発艦！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_Seaplane {
            get {
                return ResourceManager.GetString("FormCompass_Seaplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1}{2}
        ///耐久: {3}
        ///火力: {4}/{5}
        ///雷装: {6}/{7}
        ///対空: {8}/{9}
        ///装甲: {10}/{11}
        ///対潜: {12}/{13}
        ///回避: {14}/{15}
        ///索敵: {16}/{17}
        ///運: {18}/{19}
        ///(右クリックで図鑑)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_ShipInfo {
            get {
                return ResourceManager.GetString("FormCompass_ShipInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (敵艦隊情報不明) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_UnknownEnemy {
            get {
                return ResourceManager.GetString("FormCompass_UnknownEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   どうしてこうなった に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_UnknownEventID {
            get {
                return ResourceManager.GetString("FormCompass_UnknownEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   謎のアイテム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormCompass_UnknownItem {
            get {
                return ResourceManager.GetString("FormCompass_UnknownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了日時 :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormDock_CompleteTime {
            get {
                return ResourceManager.GetString("FormDock_CompleteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIリストをロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_APIListOpenDialogTitle {
            get {
                return ResourceManager.GetString("FormMain_APIListOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_APIReadError {
            get {
                return ResourceManager.GetString("FormMain_APIReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在: {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_BrowserZoomText {
            get {
                return ResourceManager.GetString("FormMain_BrowserZoomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了処理が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_CloseComplete {
            get {
                return ResourceManager.GetString("FormMain_CloseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーブしていないレコードが失われる可能性があります。
        ///ロードしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_DataNotSavedMessage {
            get {
                return ResourceManager.GetString("FormMain_DataNotSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備データが読み込まれていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_EquipmentDataNotLoaded {
            get {
                return ResourceManager.GetString("FormMain_EquipmentDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部ブラウザでオンラインヘルプを開きます。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_HelpMessage {
            get {
                return ResourceManager.GetString("FormMain_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウト ファイルは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutFileNotFound {
            get {
                return ResourceManager.GetString("FormMain_LayoutFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトが初期化されました。
        ///「表示」メニューからお好みのウィンドウを追加してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutInitializeMessage {
            get {
                return ResourceManager.GetString("FormMain_LayoutInitializeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウトを復元しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutLoadComplete {
            get {
                return ResourceManager.GetString("FormMain_LayoutLoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウトの復元に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutLoadError {
            get {
                return ResourceManager.GetString("FormMain_LayoutLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト ファイルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutOpenDialogTitle {
            get {
                return ResourceManager.GetString("FormMain_LayoutOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウトを保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutSaveComplete {
            get {
                return ResourceManager.GetString("FormMain_LayoutSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ レイアウトの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LayoutSaveError {
            get {
                return ResourceManager.GetString("FormMain_LayoutSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動処理が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LoadComplete {
            get {
                return ResourceManager.GetString("FormMain_LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先に通常の api_start2 を読み込んでください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LoadOldAPINeedDataMessage {
            get {
                return ResourceManager.GetString("FormMain_LoadOldAPINeedDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先の URL を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_NavigateMessage {
            get {
                return ResourceManager.GetString("FormMain_NavigateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先の入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_NavigateTitle {
            get {
                return ResourceManager.GetString("FormMain_NavigateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインページへ移動します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_NavigateToLoginMessage {
            get {
                return ResourceManager.GetString("FormMain_NavigateToLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除が完了しました。
        ///{0} 個のファイルを削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_OldAPIDeleteComplete {
            get {
                return ResourceManager.GetString("FormMain_OldAPIDeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_OldAPIDeleteError {
            get {
                return ResourceManager.GetString("FormMain_OldAPIDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   古いAPIデータを削除します。
        ///本当によろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_OldAPIDeleteMessage {
            get {
                return ResourceManager.GetString("FormMain_OldAPIDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旧 api_start2 からレコードを構築 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_OldAPIOpenDialogTitle {
            get {
                return ResourceManager.GetString("FormMain_OldAPIOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を終了しています… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_Quit {
            get {
                return ResourceManager.GetString("FormMain_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を終了しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_QuitMessage {
            get {
                return ResourceManager.GetString("FormMain_QuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リネーム処理が完了しました。
        ///{0} 個のアイテムをリネームしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_RenameShipResourceComplete {
            get {
                return ResourceManager.GetString("FormMain_RenameShipResourceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船リソースのリネームに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_RenameShipResourceError {
            get {
                return ResourceManager.GetString("FormMain_RenameShipResourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信から保存した艦船リソース名を持つファイル及びフォルダを、艦船名に置換します。
        ///対象は指定されたフォルダ以下のすべてのファイル及びフォルダです。
        ///続行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_RenameShipResourceMessage {
            get {
                return ResourceManager.GetString("FormMain_RenameShipResourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船リソースをリネーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_RenameShipResourceTitle {
            get {
                return ResourceManager.GetString("FormMain_RenameShipResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦船データが読み込まれていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_ShipDataNotLoaded {
            get {
                return ResourceManager.GetString("FormMain_ShipDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を起動しています… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_StartUp {
            get {
                return ResourceManager.GetString("FormMain_StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブウィンドウ レイアウトの復元に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_SubLayoutLoadError {
            get {
                return ResourceManager.GetString("FormMain_SubLayoutLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブウィンドウ レイアウトの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_SubLayoutSaveError {
            get {
                return ResourceManager.GetString("FormMain_SubLayoutSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Complete {
            get {
                return ResourceManager.GetString("MessageBox_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Confirm {
            get {
                return ResourceManager.GetString("MessageBox_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_DeleteComplete {
            get {
                return ResourceManager.GetString("MessageBox_DeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Messagebox_Error {
            get {
                return ResourceManager.GetString("Messagebox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Help {
            get {
                return ResourceManager.GetString("MessageBox_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大変ご迷惑をおかけしております に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Messagebox_MeetError {
            get {
                return ResourceManager.GetString("Messagebox_MeetError", resourceCulture);
            }
        }
    }
}
