//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Browser.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Browser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 スタイルシートの適用に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string ApplyStyleSheet_Failed {
            get {
                return ResourceManager.GetString("ApplyStyleSheet_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対象の swf が見つかりませんでした。 的本地化字符串。
        /// </summary>
        internal static string Browser_FlashNotFound {
            get {
                return ResourceManager.GetString("Browser_FlashNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document が取得できませんでした。 的本地化字符串。
        /// </summary>
        internal static string Browser_InaccessableDocument {
            get {
                return ResourceManager.GetString("Browser_InaccessableDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 embed 要素の取得に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string Browser_InaccessableFlash {
            get {
                return ResourceManager.GetString("Browser_InaccessableFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確認 的本地化字符串。
        /// </summary>
        internal static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログインページへ移動します。
        ///よろしいですか？ 的本地化字符串。
        /// </summary>
        internal static string Dialog_Login {
            get {
                return ResourceManager.GetString("Dialog_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再読み込みします。
        ///よろしいですか？ 的本地化字符串。
        /// </summary>
        internal static string Dialog_Refresh {
            get {
                return ResourceManager.GetString("Dialog_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定したプロセスIDの音量オブジェクトは存在しません。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ぴったり 的本地化字符串。
        /// </summary>
        internal static string FormBrowser_1 {
            get {
                return ResourceManager.GetString("FormBrowser_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // KCRDBと競合しないように同じように処理
        ///try {
        ///	var hideStyle = {width:&quot;0px&quot;,height:&quot;0px&quot;,visibility:&quot;hidden&quot;,display:&quot;none&quot;};
        ///	var fillStyle = {margin:&quot;0px&quot;,padding:&quot;0px&quot;,position:&quot;fixed&quot;,left:&quot;0px&quot;,top:&quot;0px&quot;,width:&quot;100%&quot;,height:&quot;100%&quot;,overflow:&quot;hidden&quot;};
        ///	var jqBody=document.body;
        ///	$(jqBody).css(&quot;zoom&quot;,&quot;normal&quot;);
        ///	$(jqBody).css({margin:&quot;0px&quot;,padding:&quot;0px&quot;,overflow:&quot;hidden&quot;});
        ///	$(&quot;#spacing_top&quot;).css(hideStyle);
        ///	$(&quot;#adFlashWrap&quot;).css(fillStyle);
        ///	$(&quot;#wsFlashWrap&quot;).css(fillStyle);
        ///	$(&quot;#flashWrap&quot;).css(fillStyle); [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FrameScript {
            get {
                return ResourceManager.GetString("FrameScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これが読み込まれていないため、スクリーンショットを撮ることはできません。 的本地化字符串。
        /// </summary>
        internal static string KanColle_NotLoaded {
            get {
                return ResourceManager.GetString("KanColle_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // KCRDBと競合しないように同じように処理
        ///try {
        ///	var hideStyle = {width:&quot;0px&quot;,height:&quot;0px&quot;,visibility:&quot;hidden&quot;,display:&quot;none&quot;};
        ///	var fillStyle = {margin:&quot;0px&quot;,padding:&quot;0px&quot;,position:&quot;fixed&quot;,left:&quot;0px&quot;,top:&quot;0px&quot;,width:&quot;100%&quot;,height:&quot;100%&quot;,overflow:&quot;hidden&quot;};
        ///	$(document.body).css({margin:&quot;0px&quot;,padding:&quot;0px&quot;,overflow:&quot;hidden&quot;});
        ///	$(&quot;img&quot;).css(hideStyle);
        ///	//$(&quot;#dmm_ntgnavi&quot;).css(hideStyle);
        ///	$(&quot;#dmm-ntgnavi-renew&quot;).css(hideStyle);
        ///	$(&quot;#w&quot;).css(fillStyle);
        ///	$(&quot;#main-ntg&quot;).css(fillStyle);
        ///	$(&quot;#page&quot;).css(fillStyle);
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PageScript {
            get {
                return ResourceManager.GetString("PageScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 これは七四式電子観測儀のサブプログラムであり、単体では起動できません。
        ///本体から起動してください。 的本地化字符串。
        /// </summary>
        internal static string Program_1 {
            get {
                return ResourceManager.GetString("Program_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 情報 的本地化字符串。
        /// </summary>
        internal static string Program_2 {
            get {
                return ResourceManager.GetString("Program_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショットの保存時にエラーが発生しました。 的本地化字符串。
        /// </summary>
        internal static string SaveScreenShot_Failed {
            get {
                return ResourceManager.GetString("SaveScreenShot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショットを {0} に保存しました。 的本地化字符串。
        /// </summary>
        internal static string SaveScreenShot_Succeed {
            get {
                return ResourceManager.GetString("SaveScreenShot_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在: {0}% 的本地化字符串。
        /// </summary>
        internal static string Zoom_CurrentText {
            get {
                return ResourceManager.GetString("Zoom_CurrentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズームの適用に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string Zoom_Failed {
            get {
                return ResourceManager.GetString("Zoom_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在: ぴったり 的本地化字符串。
        /// </summary>
        internal static string Zoom_FitText {
            get {
                return ResourceManager.GetString("Zoom_FitText", resourceCulture);
            }
        }
    }
}
