//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Browser.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Browser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   // KCRDBと競合しないように同じように処理
        ///try {
        ///	var hideStyle = {width:&quot;0px&quot;,height:&quot;0px&quot;,visibility:&quot;hidden&quot;,display:&quot;none&quot;};
        ///	var fillStyle = {margin:&quot;0px&quot;,padding:&quot;0px&quot;,position:&quot;fixed&quot;,left:&quot;0px&quot;,top:&quot;0px&quot;,width:&quot;100%&quot;,height:&quot;100%&quot;,overflow:&quot;hidden&quot;};
        ///	var jqBody=document.body;
        ///	$(jqBody).css(&quot;zoom&quot;,&quot;normal&quot;);
        ///	$(jqBody).css({margin:&quot;0px&quot;,padding:&quot;0px&quot;,overflow:&quot;hidden&quot;});
        ///	$(&quot;#spacing_top&quot;).css(hideStyle);
        ///	$(&quot;#adFlashWrap&quot;).css(fillStyle);
        ///	$(&quot;#wsFlashWrap&quot;).css(fillStyle);
        ///	$(&quot;#flashWrap&quot;).css(fillStyle); [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FrameScript {
            get {
                return ResourceManager.GetString("FrameScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // KCRDBと競合しないように同じように処理
        ///try {
        ///	var hideStyle = {width:&quot;0px&quot;,height:&quot;0px&quot;,visibility:&quot;hidden&quot;,display:&quot;none&quot;};
        ///	var fillStyle = {margin:&quot;0px&quot;,padding:&quot;0px&quot;,position:&quot;fixed&quot;,left:&quot;0px&quot;,top:&quot;0px&quot;,width:&quot;100%&quot;,height:&quot;100%&quot;,overflow:&quot;hidden&quot;};
        ///	$(document.body).css({margin:&quot;0px&quot;,padding:&quot;0px&quot;,overflow:&quot;hidden&quot;});
        ///	$(&quot;img&quot;).css(hideStyle);
        ///	//$(&quot;#dmm_ntgnavi&quot;).css(hideStyle);
        ///	$(&quot;#dmm-ntgnavi-renew&quot;).css(hideStyle);
        ///	$(&quot;#w&quot;).css(fillStyle);
        ///	$(&quot;#main-ntg&quot;).css(fillStyle);
        ///	$(&quot;#page&quot;).css(fillStyle);
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PageScript {
            get {
                return ResourceManager.GetString("PageScript", resourceCulture);
            }
        }
		
		/// <summary>
        ///   スタイルシートの適用に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyStyleSheet_Failed {
            get {
                return ResourceManager.GetString("ApplyStyleSheet_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の swf が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Browser_FlashNotFound {
            get {
                return ResourceManager.GetString("Browser_FlashNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   embed 要素の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Browser_InaccessableFlash {
            get {
                return ResourceManager.GetString("Browser_InaccessableFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインページへ移動します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Login {
            get {
                return ResourceManager.GetString("Dialog_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再読み込みします。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Refresh {
            get {
                return ResourceManager.GetString("Dialog_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦これが読み込まれていないため、スクリーンショットを撮ることはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KanColle_NotLoaded {
            get {
                return ResourceManager.GetString("KanColle_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットの保存時にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveScreenShot_Failed {
            get {
                return ResourceManager.GetString("SaveScreenShot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットを {0} に保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveScreenShot_Succeed {
            get {
                return ResourceManager.GetString("SaveScreenShot_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在: {0}% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Zoom_CurrentText {
            get {
                return ResourceManager.GetString("Zoom_CurrentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズームの適用に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Zoom_Failed {
            get {
                return ResourceManager.GetString("Zoom_Failed", resourceCulture);
            }
        }
		
        /// <summary>
        ///   現在: ぴったり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Zoom_FitText {
            get {
                return ResourceManager.GetString("Zoom_FitText", resourceCulture);
            }
        }
		
        /// <summary>
        ///   指定したプロセスIDの音量オブジェクトは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Volume_PIDNotFound {
            get {
                return ResourceManager.GetString("Volume_PIDNotFound", resourceCulture);
            }
        }
		
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
		
        /// <summary>
        ///   これは七四式電子観測儀のサブプログラムであり、単体では起動できません。
        ///本体から起動してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dialog_EmptyParameter {
            get {
                return ResourceManager.GetString("Dialog_EmptyParameter", resourceCulture);
            }
        }
    }
}
